// Generated by CoffeeScript 1.10.0
(function() {
  var checkDate, dateKeeper, transformDate;

  transformDate = function(date) {
    var day, month, result, year;
    day = date.getDate();
    if (day < 10) {
      day = "0" + day;
    }
    month = date.getMonth() + 1;
    if (month < 10) {
      month = "0" + month;
    }
    year = date.getFullYear();
    return result = parseInt("" + year + month + day);
  };

  dateKeeper = function() {
    var lastDate, lastDateInt;
    lastDate = void 0;
    lastDateInt = void 0;
    return function() {
      var currentDate, currentDateInt;
      if (!lastDate) {
        lastDate = new Date();
        lastDateInt = transformDate(lastDate);
        return lastDate;
      } else {
        currentDate = new Date();
        currentDateInt = transformDate(currentDate);
        if (currentDateInt === lastDateInt) {
          return null;
        } else {
          lastDate = currentDate;
          lastDateInt = currentDateInt;
          return lastDate;
        }
      }
    };
  };

  checkDate = dateKeeper();

  exports.checkDate = checkDate;

}).call(this);
