// Generated by CoffeeScript 1.10.0
(function() {
  var formate, fs;

  fs = require('fs');

  formate = function(data) {
    var result;
    data = JSON.parse(data);
    result = data.directory + "\t" + data.filename + "\t" + data.event + "\t" + data.date + "\n";
    return fs.appendFile('watcher-log.txt', result, function(err) {
      if (err) {
        throw err;
      }
    });
  };

  exports.formate = formate;

}).call(this);
