// Generated by CoffeeScript 1.10.0
(function() {
  var fs, isCritical, writeLog;

  fs = require('fs');

  isCritical = function(data) {
    var event, filename;
    event = data.event;
    filename = data.filename;
    if (event === "CREATE" || event === "MODIFY" || event === "DELETE" || (event.search(/MOVE/) >= 0)) {
      if (filename.search(/\.php$/) >= 0 || filename.search(/\.html$/) >= 0 || filename.search(/\.js$/) >= 0) {
        return true;
      }
    } else {
      return false;
    }
  };

  writeLog = function(data, logPath) {
    var criticalLogFile, logFile, result;
    data = JSON.parse(data);
    result = data.directory + "\t" + data.filename + "\t" + data.event + "\t" + data.date + "\n";
    logFile = logPath + "/watcher.log";
    criticalLogFile = logPath + "/critical.log";
    if (isCritical(data)) {
      fs.appendFile(criticalLogFile, result, function(err) {
        if (err) {
          throw err;
        }
      });
    }
    return fs.appendFile(logFile, result, function(err) {
      if (err) {
        throw err;
      }
    });
  };

  exports.writeLog = writeLog;

}).call(this);
