// Generated by CoffeeScript 1.10.0
(function() {
  var fs, writeLog;

  fs = require('fs');

  writeLog = function(data, logPath) {
    var logFile, result;
    data = JSON.parse(data);

    /*
    filename = data.filename
    
    
    if (filename.search(/\.php$/) || filename.search(/\.html$/) || filename.search(/\.js$/))
      console.log "!!!!"
     */
    result = data.directory + "\t" + data.filename + "\t" + data.event + "\t" + data.date + "\n";
    logFile = logPath + "/watcher-log.txt";
    return fs.appendFile(logFile, result, function(err) {
      if (err) {
        throw err;
      }
    });
  };

  exports.writeLog = writeLog;

}).call(this);
