// Generated by CoffeeScript 1.10.0
(function() {
  var checkFileType, fs, isCritical, writeLog;

  fs = require('fs');

  checkFileType = function(types, filename) {
    var flags, i, j, len, reg, res, type;
    res = false;
    for (j = 0, len = types.length; j < len; j++) {
      type = types[j];
      if (!res) {
        reg = "\\." + type + "$";
        flags = 'gi';
        reg = new RegExp(reg, flags);
        if (i = filename.search(reg) >= 0) {
          res = true;
        } else {
          res = false;
        }
      }
    }
    return res;
  };

  isCritical = function(data, critFTypes) {
    var event, filename;
    event = data.event;
    filename = data.filename;
    if (event === "CREATE" || event === "MODIFY" || event === "DELETE" || (event.search(/MOVE/) >= 0)) {
      return checkFileType(critFTypes, filename);
    } else {
      return false;
    }
  };

  writeLog = function(data, logPath, critFTypes) {
    var criticalLogFile, logFile, result;
    data = JSON.parse(data);
    result = data.directory + "\t" + data.filename + "\t" + data.event + "\t" + data.date + "\n";
    logFile = logPath + "/watcher.log";
    criticalLogFile = logPath + "/critical.log";
    if (isCritical(data, critFTypes)) {
      fs.appendFile(criticalLogFile, result, function(err) {
        if (err) {
          throw err;
        }
      });
    }
    return fs.appendFile(logFile, result, function(err) {
      if (err) {
        throw err;
      }
    });
  };

  exports.writeLog = writeLog;

}).call(this);
