// Generated by CoffeeScript 1.10.0
(function() {
  var watch, watchPath;

  watch = (require('./watch.js')).watch;

  watchPath = process.argv[2] || (function() {
    throw "НЕ УКАЗАНА ДИРРЕКТОРИЯ ДЛЯ СЛЕЖЕНИЯ";
  })();

  watch(watchPath);

}).call(this);
