// Generated by CoffeeScript 1.10.0
(function() {
  var config, critFTypes, fs, logPath, setLogFolder, watch, watchPath;

  fs = require('fs');

  watch = (require('./watch.js')).watch;

  if (process.argv[2]) {
    if (process.argv[2] === "--config") {
      if (process.argv[3]) {
        config = require("./" + process.argv[3]);
        watchPath = config.watchPath || (function() {
          throw "undefined watch directory in config file";
        })();
        logPath = config.logPath || (function() {
          throw "undefined log directory in config file";
        })();
        critFTypes = config.criticalFileTypes || void 0;
      } else {
        throw "CONFIG FILE IS MISSING";
      }
    } else {
      watchPath = process.argv[2] || (function() {
        throw "WATCH FOLDER IS NOT DEFINED";
      })();
      logPath = process.argv[3] || (function() {
        throw "LOG FOLDER IS NOT DEFINED";
      })();
    }
  } else {
    throw "NO PARAMETRS SET";
  }

  critFTypes = critFTypes || ["php", "js"];

  setLogFolder = function(logPath, cb) {
    return fs.stat(logPath, function(err, stats) {
      if (err) {
        throw "ERROR: Log directory does not exist --> " + err;
      } else if (!stats.isDirectory()) {
        throw "ERROR: " + logPath + " is not a directory";
      } else {
        return cb(watchPath, logPath, critFTypes);
      }
    });
  };

  setLogFolder(logPath, watch);

}).call(this);
