// Generated by CoffeeScript 1.10.0
(function() {
  var checkUser, fs;

  fs = require('fs');

  checkUser = function(filename) {
    var options, result, spawn, userCheck;
    result = "";
    spawn = (require('child_process')).spawnSync;
    options = [filename, "--format=uid %u - %U"];
    userCheck = spawn('stat', options);
    result = userCheck.stdout.toString();
    result = result.replace("\n", "");
    if (result) {
      return result;
    } else {
      return void 0;
    }
  };

  exports.checkUser = checkUser;

}).call(this);
