// Generated by CoffeeScript 1.10.0
(function() {
  var lib, watch;

  lib = require('./lib.js');

  watch = function(watchPath, logPath) {
    var options, spawn, watcher;
    spawn = (require('child_process')).spawn;
    options = ['-mr', '--timefmt', '%d-%b-%Y %H:%M', '--format', '{"directory":"%w", "filename":"%f", "event":"%_e", "date":"%T"}', watchPath];
    watcher = spawn('inotifywait', options);
    watcher.stdout.on('data', function(data) {
      var element, i, len, results, str;
      str = data.toString();
      str = str.split("\n");
      results = [];
      for (i = 0, len = str.length; i < len; i++) {
        element = str[i];
        if (element) {
          results.push(lib.formate(element, logPath));
        } else {
          results.push(void 0);
        }
      }
      return results;
    });
    watcher.stderr.on('data', function(data) {
      return console.log("ERROR! --> " + data);
    });
    return watcher.on("close", function() {
      return console.log("\n ---> EXIT --->\n");
    });
  };

  exports.watch = watch;

}).call(this);
